# Cargo audit configuration

[advisories]
# Ignore specific advisories that have no available fix
ignore = [
    "RUSTSEC-2023-0071", # RSA timing sidechannel in openidconnect - no fix available
]

# Warn about unmaintained crates but don't fail
informational_warnings = ["unmaintained"]

[output]
# Deny warnings from these specific vulnerability classes
deny = ["yanked"]

# Output format
quiet = false